language: node_js
node_js:
  - '12.16.1'
install:
  - yarn install:all

cache:
  yarn: true
  directories:
    - ~/.cache

before_deploy:
  - yarn build:client
  - cp -r './client/build/.' './server/static'

deploy:
  - echo 'We should deploy here & we are champions'

script:
  - echo "skipping tests"
