language: node_js
node_js:
  - '12.16.1'
install:
  - yarn install:all

cache:
  yarn: true
  directories:
    - node_modules
    - ~/.cache

before_deploy:
  - yarn build:client
  - yarn post_build:copy

deploy:
  - echo 'We should deploy here'

script:
  - echo "skipping tests"
